spring.profiles.active=local


# ===== user IP temp cleanup =====
# ??? ????? ??????? ?????? IP ????????????? (? ????????)
user.ip.ttl-seconds=300
# ???????? ????? ???????? ??????? (? ?????????????)
user.ip.cleanup-interval-ms=300000
