spring.profiles.active=local
#spring.profiles.active=prod


# ===== user IP temp cleanup =====
# how long to keep user IP entries (in seconds)
user.ip.ttl-seconds=300
# interval between cleanup tasks (in milliseconds)
user.ip.cleanup-interval-ms=300000