#spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
spring.profiles.active=dev


# ===== user IP temp cleanup =====
# ??? ????? ??????? ?????? IP ????????????? (? ????????)
user.ip.ttl-seconds=300
# ???????? ????? ???????? ??????? (? ?????????????)
user.ip.cleanup-interval-ms=300000
